### ISSUE TITLE
Feature correlation p-values and correction methods

### ISSUE THREAD

**Issue by feribg** [parrt/random-forest-importances#10]
Wanted to get the conversation open on feature correlation, right now it just does a naive spearmanr, with no insight into the resulting p-values. Would be great to do a few things, listed below in order of importance:

1. Introduce p-values and maybe apply the appropriate cutoffs
2. Introduce permutation based correlation, starting off with lagged correlations for example (context is time series analysis)
3. Introduce a probability correction method for 1 and/or 2 such as bonferroni, to account for the number of correlation estimates we're doing between features and between number of lags if we end up implementing #2. 

Happy to get the conversation going and see where we end up. Right now the feature correlation estimation is not quite stable in the context of very noisy time series data.

**Comment by feribg** [comment]
@parrt I had a look at this function and it's a good starting point to use as a base but I have several questions/comments around it, because it seems you've modified the code above and it's different from what's there on master now (which seems broken to me):

1. It assumes a random forest classifier (presumably the same one that we use for the final model. The problem is a lot of the variables that are used as features are continuous so when converting them to targets the whole thing falls apart. (You substituted for a regressor above, but i guess we should provide a flex impl as a param)
2. These couple of lines are a bit ambiguous to me:
```
imp = permutation_importances_raw(rf, X, y, oob_regression_r2_score, n_samples)
imp = np.insert(imp, i, 1.0)
df_dep.iloc[i] = np.insert(imp, 0, rf.oob_score_) # add overall dependence
```
Why are we using the oob_regression_r2 and what's it's meaning, seems like we want classification but are running r2 as a scoring function, which is confusing to me.
3. To the above, should we not add support for val_set, if oob_score_ is not reliable or not present at all.
Happy to discuss and cleanup that function first in master than build on top of it.

**Comment by parrt** [comment]
Hi.  I don't think I'm going to be pushing too many new features into this package so I will close this to clean up.

**Comment by feribg** [comment]
@parrt fair, this is I think a more full fledged library that uses the same method at it's core with some extra statistical tweaks:
https://github.com/scikit-learn-contrib/boruta_py
