### ISSUE TITLE
SyntaxError in python2.7

### ISSUE THREAD

**Issue by diego-mazon** [parrt/random-forest-importances#11]
Syntax error in python2.7 (it does work python3). If rfpimp is not supposed to work in 2.7, you might want to consider mentioning it in the README

`import rfpimp`

File "/Users/diegomazon/anaconda/lib/python2.7/site-packages/rfpimp.py", line 40
    self.svgfilename = f"{tmp}/PimpViz_{getpid()}.svg"
                                                     ^
SyntaxError: invalid syntax

**Comment by parrt** [comment]
oh good point! Forgot to check that.

**Comment by sand9888** [comment]
do I understand correctly that rfpimp works python 3.6 and above only?
f"{tmp}/PimpViz_{getpid()}.svg" - looks like this type of string formatting is not actual for python 3.5

**Comment by parrt** [comment]
oh wow. even 3.5 doesn't have?  maybe i'll just fix those and see if i can downgrade.

**Comment by PanditPranav** [comment]
I have the same issue with both Python 2.7 and 3.5. Should I upgrade to 3.6?

**Comment by parrt** [comment]
for now, yep
