### ISSUE TITLE
TypeError: barh() missing 1 required positional argument: 'bottom'

### ISSUE THREAD

**Issue by TNFCFA** [parrt/random-forest-importances#13]
Installed the package and working thru your Classifier example on rents.  https://github.com/parrt/random-forest-importances/blob/master/notebooks/permutation-importances-classifier.ipynb

Immediately get the missing argument error in block 3 of the notebook.  have searched the rfImp functions and do not see where it could be missing.

**Comment by parrt** [comment]
hi. just a quick check, did you `pip install -U rfpimp` to ensure latest version?  Is your jupyter using same python as `pip`?

**Comment by TNFCFA** [comment]
I did pip install rfpimp.  Am using Python 3.6 and not Anconda/Jupyter.  I have made all the needed changes for this but cannot determine the 'bottom' arg in the plot

**Comment by parrt** [comment]
maybe it's an issue of barh() being different in previous matplotlib versions.

**Comment by parrt** [comment]
Ping @TNFCFA

**Comment by lissue** [comment]
I had the same error message on a machine running matplotlib 2.0.2. Removing y= and width= worked for me. Removing them still allows it to function on newer versions of matplotlib.

**Comment by parrt** [comment]
Would still love to get a snippet of code that doesn't work...
