### ISSUE TITLE
sparse matrix as input

### ISSUE THREAD

**Issue by 1fmusic** [parrt/random-forest-importances#22]
HI. First of all this work is amazing. Thank you for this contribution and for explaining the issues with RF default importance so clearly. 

 I am working with a large dataset (term-document matrix) and am using a sparse matrix (scipy csr) as my input for the model. I wanted to know if you have any suggestions about how to implement the dropcol_importances functionality without changing to a pandas df (too large).  The 'rows' of the csr are my features. 

Currently thinking I will need to convert to a COO, remove all the rows with feature (x), then convert back to sparse matrix for each iteration. 

I'm currently searching for efficient ways. and thought i would ask you about it.   
Thank you again for all your contributions. 
Regards, 
Summer

**Comment by parrt** [comment]
Hi. Hmm...It might work simply to do `pd.DataFrame(data=matrix)` but for very large data set there could be a problem. or, just look at the article associated with this repo and copy the algorithm and make it work on the sparse matrix.
