### ISSUE TITLE
Overload inbuilt sklearn feature_importance for use with RFECV

### ISSUE THREAD

**Issue by Zylatis** [parrt/random-forest-importances#24]
I'm currently muddling through learning my way around the pitfalls of various importance measures, and one thing I'm aiming for (along with everyone else) is more automated feature selection. To this end 

https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFECV.html

is very handy but it would be nice to be able to use the definitions (specifically the drop/permute importances) from ```rfpimp``` there - what would be the best way to go about this? One way would seem to be to overload the sklearn RF itself or a branch of it, but perhaps more useful and modular would be to fork the RFECV into ```rfpimp``` and use it from there. 

Thanks!
Z

**Comment by parrt** [comment]
Hi.  I think what I normally do is use a loop that removes a feature at a time and recompute feature importance to make sure validation error does not start going up. or at least stopping when it does go up.
