### ISSUE TITLE
Use df.corr('spearman') instead of scipy.stats.spearmanr, to deal with dfs with NaNs

### ISSUE THREAD

**Issue by xoelop** [parrt/random-forest-importances#25]
I'm dealing with a dataset of answers to a questionnaire. Each person receives 8 questions out of 12 possible ones, so there's a 33% of NaNs. It's like this
![image](https://user-images.githubusercontent.com/8508402/69175637-05966480-0afc-11ea-94f0-723a449c3073.png)

To pass the quiz, you need to get 5 right. I'm trying to figure out the importance of each one of those questions to reduce the number of questions and make it shorter, while still having relevant information.

I tried to use the `plot_corr_heatmap` function, but it gives errors because the input DataFrame can't contain NaN values. For this step of calculating the correlation between variables, I don't think it's right to fillna them with another value, as that would distort the data in a significant way (even tho I did it to train a Random Forest Classifier on it).

I saw that plot_corr_heatmap is calling internally `scipy.stats.spearmanr`, which doesn't accept NaNs.

But pandas DataFrames have a `df.corr() `method that can take 'spearman' as a parameter, and accept NaNs, so that would make `plot_corr_heatmap` usable in cases like this

What do you think, @parrt? Should I submit a PR? 

![image](https://user-images.githubusercontent.com/8508402/69176119-08de2000-0afd-11ea-88ed-8b88c731afa0.png)

**Comment by parrt** [comment]
Hi @xoelop! A PR would be great! Thanks for catching this.

**Comment by parrt** [comment]
I believe this is fixed by https://github.com/parrt/random-forest-importances/pull/43   Pushing 1.3.6 shortly.
