### ISSUE TITLE
Error with oob_importances with scikit-learn 0.22.1

### ISSUE THREAD

**Issue by mkhan037** [parrt/random-forest-importances#27]
`oob_importances` internally uses `_generate_unsampled_indices` which is a private function within scikit-learn. In scikit-learn 0.22.1 the function signature of `_generate_unsampled_indices` has changed from 
`_generate_unsampled_indices(random_state, n_samples)` to
`_generate_unsampled_indices(random_state, n_samples, n_samples_bootstrap)` . 
This signature change can be seen [here](https://github.com/scikit-learn/scikit-learn/blob/e5698bde9a8b719514bf39e6e5d58f90cfe5bc01/sklearn/ensemble/_forest.py#L125)

**Comment by parrt** [comment]
Thanks! I'll  have to look at that.

**Comment by niskrev** [comment]
`feature_dependence_matrix` method gives an error for the same reason (depends on `oob_regression_r2_score ` which also calls `_generate_unsampled_indices`)

**Comment by parrt** [comment]
Hmm...i wonder how to make it backward compatible.

**Comment by standardAI** [comment]
Same error.
