### ISSUE TITLE
Why is this package using R2 as the criterion to evaluate error rate for regression?

### ISSUE THREAD

**Issue by PowderL** [parrt/random-forest-importances#28]
There was a classical package in R named "randomForest"  based on  Leo Breiman and Adele Cutler's Fortran code. They used mean-squared-error as the criterion to evaluate the variable importance before and after permutation. I have read the python code for this package. I find the criterion is R2 which is different with the R package. Is the R2 criterion more better? Or, I just misunderstand the python code. Thanks a lot in advance for answering my questions!

**Comment by parrt** [comment]
I think only the OOB uses the (default) R2.  I believe we allow you to pass in a metric now for other functions.

**Comment by PowderL** [comment]
Great, thank you a lot!
