### ISSUE TITLE
ImportError: cannot import name plot_corr_heatmap

### ISSUE THREAD

**Issue by Shoresh92** [parrt/random-forest-importances#3]
Using the library, I get the following error:

    ImportError: cannot import name plot_corr_heatmap

This function does not exist in my rfpimp library. Am I using the older version or am missing something? I followed the instructions in [here](http://parrt.cs.usfca.edu/doc/rf-importance/index.html#4).

**Comment by parrt** [comment]
Hi. please `pip install -U rfpimp` to get the latest :)

**Comment by Shoresh92** [comment]
I thought I already tried this. Problem fixed. Thank you!
