### ISSUE TITLE
FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24

### ISSUE THREAD

**Issue by tpvasconcelos** [parrt/random-forest-importances#30]
This import statement 

https://github.com/parrt/random-forest-importances/blob/d0b4e99a9f59ab3dd982ea8c59a94e2bbee55209/src/rfpimp.py#L15

is raising the following `FutureWarning`

```
 FutureWarning:
The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
```

This could easily be solved by implementing the simple function in `rfpimp`.

**Comment by parrt** [comment]
Hmm...I wonder if there's a way to make it work in both versions
