### ISSUE TITLE
Variable importances differ with subsequent calls.

### ISSUE THREAD

**Issue by anilkumarpanda** [parrt/random-forest-importances#31]
rfpimp package returns different variable importances for subsequent calls to the function.

![Screenshot 2020-05-04 at 22 36 43](https://user-images.githubusercontent.com/7496719/81011176-ca90af00-8e57-11ea-9e7f-15c8b7300ff1.png)

The entire code to reproduce this can be found here : 
https://github.com/anilkumarpanda/introduction_to_ml/blob/master/03.LinearModels/Bank_Marketing-Answers.ipynb

One reason I can think of is that in this case the feature importances are low, hence they are not very stable. Is this the case or am I missing something else?

**Comment by matheusccouto** [comment]
The explanation for this behavior can be found here:
[Dealing with collinear features](https://explained.ai/rf-importance/index.html#corr_collinear)

**Comment by parrt** [comment]
It could also be your model but it looks like your accuracy is ok. Could be the one-hot encoding. you don't need cat level importance, just cat importance usually. RFs also don't need one-hot.
