### ISSUE TITLE
TypeError: _generate_unsampled_indices() missing 1 required positional argument: 'n_samples_bootstrap'

### ISSUE THREAD

**Issue by Yanjiayork** [parrt/random-forest-importances#33]
Hello there, after I installed the  library, I tested the example code that "rf = RandomForestRegressor(n_estimators=100, n_jobs=-1, oob_score=True)
    X_train, y_train = ..., ...
    rf.fit(X_train, y_train)
    imp = oob_importances(rf, X_train, y_train)"

And it shows the error as below:

**rf = RandomForestClassifier(n_estimators=100, n_jobs=-1, oob_score=True)
rf.fit(x, y)
imp = oob_importances(rf, x, y)**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-cefe24b414bb> in <module>
      1 rf = RandomForestClassifier(n_estimators=100, n_jobs=-1, oob_score=True)
      2 rf.fit(x, y)
----> 3 imp = oob_importances(rf, x, y)

~/anaconda/envs/py36/lib/python3.6/site-packages/rfpimp.py in oob_importances(rf, X_train, y_train, n_samples)
    231     """
    232     if isinstance(rf, RandomForestClassifier):
--> 233         return permutation_importances(rf, X_train, y_train, oob_classifier_accuracy, n_samples)
    234     elif isinstance(rf, RandomForestRegressor):
    235         return permutation_importances(rf, X_train, y_train, oob_regression_r2_score, n_samples)

~/anaconda/envs/py36/lib/python3.6/site-packages/rfpimp.py in permutation_importances(rf, X_train, y_train, metric, n_samples)
    282 
    283 def permutation_importances(rf, X_train, y_train, metric, n_samples=5000):
--> 284     imp = permutation_importances_raw(rf, X_train, y_train, metric, n_samples)
    285     I = pd.DataFrame(data={'Feature':X_train.columns, 'Importance':imp})
    286     I = I.set_index('Feature')

~/anaconda/envs/py36/lib/python3.6/site-packages/rfpimp.py in permutation_importances_raw(rf, X_train, y_train, metric, n_samples)
    398         rf.fit(X_sample, y_sample)
    399 
--> 400     baseline = metric(rf, X_sample, y_sample)
    401     X_train = X_sample.copy(deep=False) # shallow copy
    402     y_train = y_sample

~/anaconda/envs/py36/lib/python3.6/site-packages/rfpimp.py in oob_classifier_accuracy(rf, X_train, y_train)
    427     predictions = np.zeros((n_samples, n_classes))
    428     for tree in rf.estimators_:
--> 429         unsampled_indices = _generate_unsampled_indices(tree.random_state, n_samples)
    430         tree_preds = tree.predict_proba(X[unsampled_indices, :])
    431         predictions[unsampled_indices] += tree_preds

**TypeError: _generate_unsampled_indices() missing 1 required positional argument: 'n_samples_bootstrap'**

Could you please help on this?

Many thanks

Yan

**Comment by parrt** [comment]
Hi. Yep, it's a backward compatibility issue with sklearn. I'll resolve when I can.
