### ISSUE TITLE
'RandomForestRegressor' object has no attribute 'estimators_'

### ISSUE THREAD

**Issue by miaomaggie** [parrt/random-forest-importances#39]
When I use the function 'oob_regression_r2_score()',  "**AttributeError: 'RandomForestRegressor' object has no attribute 'estimators_**'"

def oob_regression_r2_score(rf, X_train, y_train):
    """
    Compute out-of-bag (OOB) R^2 for a scikit-learn random forest
    regressor. We learned the guts of scikit's RF from the BSD licensed
    code:
    https://github.com/scikit-learn/scikit-learn/blob/a24c8b46/sklearn/ensemble/forest.py#L702
    """
    X = X_train.values if isinstance(X_train, pd.DataFrame) else X_train
    y = y_train.values if isinstance(y_train, pd.Series) else y_train

    n_samples = len(X)
    predictions = np.zeros(n_samples)
    n_predictions = np.zeros(n_samples)
    
    
    for tree in rf.estimators_:
        unsampled_indices = _get_unsampled_indices(tree, n_samples)
        tree_preds = tree.predict(X[unsampled_indices, :])
        predictions[unsampled_indices] += tree_preds
        n_predictions[unsampled_indices] += 1

    if (n_predictions == 0).any():
        warnings.warn("Too few trees; some variables do not have OOB scores.")
        n_predictions[n_predictions == 0] = 1

    predictions /= n_predictions

    oob_score = r2_score(y, predictions)
    return oob_score

def permutation_importances(rf, X_train, y_train, metric):
    baseline = metric(rf, X_train, y_train)
    imp = [] 
    for col in X_train.columns:
        save = X_train[col].copy() 
        X_train[col] = np.random.permutation(X_train[col])
        m = metric(rf, X_train, y_train) 
        X_train[col] = save 
        imp.append(baseline - m) 
    return np.array(imp)

rf = RandomForestRegressor(n_estimators=100)
imp = permutation_importances(rf, X_train, y_train, oob_regression_r2_score)

**Comment by parrt** [comment]
must call fit() first?

**Comment by miaomaggie** [comment]
> must call fit() first?

Yes！Brilliant！Thank you~
