### ISSUE TITLE
Dropcol depends on OOB score

### ISSUE THREAD

**Issue by feribg** [parrt/random-forest-importances#4]
It seems that the dropcol importance depends on the oob_score which might not be available or accurate in many cases depending on the problem. Would it make sense to submit a PR that checks for the full model metric vs constrained model metric on a validation set and not OOB?

**Comment by parrt** [comment]
howdy! Yes, maybe we need to rename that oob_dropcol_importances and then make a general dropcol_importances that uses a validation set?

**Comment by feribg** [comment]
Sounds good, I will work on those 2 PRs in the upcoming few days. Also thinking of generalizing the metric to be a list or a single metric in case we'd like to monitor the change in multiple metrics at once? Not sure how much more overhead in terms of impl that would be, but might make sense.

**Comment by parrt** [comment]
Well, I think we can start simply and just pass in a single metric.
