### ISSUE TITLE
plot_dependence_heatmap doesn't work for sklearn 0.23

### ISSUE THREAD

**Issue by Zianor** [parrt/random-forest-importances#41]
You fixed the argument problem for sklearn 0.22 in a previous [commit](https://github.com/parrt/random-forest-importances/commit/78fc21495e7e351ea1cf09b7be1a1b829bb18af5), but it would be great, if you could do it for newer versions as well
![bug](https://user-images.githubusercontent.com/16058316/96690289-c4e64180-1383-11eb-8df6-46ac85120bd8.png)

**Comment by parrt** [comment]
Ah.  so instead of checking specifically for 0.22 we look for anything greater than or equal to?

**Comment by Zianor** [comment]
> Ah. so instead of checking specifically for 0.22 we look for anything greater than or equal to?

Yes. I guess casting to an int and checking

**Comment by parrt** [comment]
Ah.  it turns out that this is been fixed already but I haven't pushed out a new version.  fixed by https://github.com/parrt/random-forest-importances/pull/36
