### ISSUE TITLE
Incompatible with latest version of sklearn

### ISSUE THREAD

**Issue by yuchaoran2011** [parrt/random-forest-importances#44]
In https://github.com/scikit-learn/scikit-learn/pull/14964, modules in ensemble have been made private, breaking this [line](https://github.com/parrt/random-forest-importances/blob/1.3.6/src/rfpimp.py#L16) of code (`forest` has become `_forest`).

**Comment by parrt** [comment]
Dang!  Is this a 0.23 version compatibility issue? I.e., will I have to check the version of sklearn in the code at:
https://github.com/parrt/random-forest-importances/blob/1.3.6/src/rfpimp.py#L16 ??

**Comment by yuchaoran2011** [comment]
@parrt Thanks for the quick response. The compatibility got broken for sklearn version 0.22.0 and above (It works for 0.21.3 and earlier)

**Comment by parrt** [comment]
Dang.  I could swear I did something about compatibility recently on this. Ah.  apparently I didn't do a complete job but here is the previous thing I did: https://github.com/parrt/random-forest-importances/pull/35

**Comment by Sharpen6** [comment]
This should solve it.
tested on python3.7 with sklearn 0.23.2 & 0.24.0

from distutils.version import LooseVersion
...

**if LooseVersion(sklearn.__version__) >= LooseVersion("0.24"):
    # In sklearn version 0.24, forest module changed to be private.
    from sklearn.ensemble._forest import _generate_unsampled_indices
    from sklearn.ensemble import _forest as forest
else:
    # Before sklearn version 0.24, forest was public, supporting this.
    from sklearn.ensemble.forest import _generate_unsampled_indices
    from sklearn.ensemble import forest**

...

Anyone with writing permissions- please commit this :)

**Comment by parrt** [comment]
Thanks @Sharpen6 !!!  Fixed by https://github.com/parrt/random-forest-importances/pull/45
