### ISSUE TITLE
'deep' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by ebuka-nweke** [parrt/random-forest-importances#46]
I am trying to get the feature importance of my random forest model but i keep getting the following error:

'deep' is an invalid keyword argument for this function

Below is the entire error output:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-98ee1ab660fa> in <module>()
      1 #getting imortance for features using permutation importance
      2 
----> 3 perm_imp_rfpimp_rf10 = permutation_importances(rf_10, train_features_x, train_labels_y, rdt10)
      4 perm_imp_rfpimp_rf100 = permutation_importances(rf_100, train_features_x, train_labels_y, rdt100)
      5 perm_imp_rfpimp_rf1000 = permutation_importances(rf_1000, train_features_x, train_labels_y, rdt1000)

~/anaconda2/envs/py36/lib/python3.6/site-packages/rfpimp.py in permutation_importances(rf, X_train, y_train, metric, n_samples)
    286 
    287 def permutation_importances(rf, X_train, y_train, metric, n_samples=5000):
--> 288     imp = permutation_importances_raw(rf, X_train, y_train, metric, n_samples)
    289     I = pd.DataFrame(data={'Feature':X_train.columns, 'Importance':imp})
    290     I = I.set_index('Feature')

~/anaconda2/envs/py36/lib/python3.6/site-packages/rfpimp.py in permutation_importances_raw(rf, X_train, y_train, metric, n_samples)
    403 
    404     baseline = metric(rf, X_sample, y_sample)
--> 405     X_train = X_sample.copy(deep=False,axes=True) # shallow copy
    406     y_train = y_sample
    407     imp = []

TypeError: 'deep' is an invalid keyword argument for this function

My inputs involve providing a function based metric as below:
---------------------------------------------------------------------------

def rdt10(rf_10,train_features_x, train_labels_y):
    return r2_score(train_labels_y, rf_10.predict(train_features_x))

def rdt100(rf_100,train_features_x, train_labels_y):
    return r2_score(train_labels_y, rf_100.predict(train_features_x))

def rdt1000(rf_1000,train_features_x, train_labels_y):
    return r2_score(train_labels_y, rf_1000.predict(train_features_x)) 

and then calling it in the permutation importance function below (this is what gives the error output from above):

perm_imp_rfpimp_rf10 = permutation_importances(rf_10, train_features_x, train_labels_y, rdt10)
perm_imp_rfpimp_rf100 = permutation_importances(rf_100, train_features_x, train_labels_y, rdt100)
perm_imp_rfpimp_rf1000 = permutation_importances(rf_1000, train_features_x, train_labels_y, rdt1000)

rf_10, rf_100, rf_1000 are my random forest models using 10, 100, and 1000 estimators.

Please help me figure out how to address this error:

**Comment by parrt** [comment]
Weird. `X_sample.copy(deep=False,axes=True)` getting error must mean `X_sample` is not a dataframe or maybe sklearn has changed?

**Comment by ebuka-nweke** [comment]
> Weird. `X_sample.copy(deep=False,axes=True)` getting error must mean `X_sample` is not a dataframe or maybe sklearn has changed?

I am not sure. 

The dataset it is sampling from is in the form of a pandas data frame. So i am not sure.

**Comment by parrt** [comment]
What version of pandas?

**Comment by ebuka-nweke** [comment]
> What version of pandas?

I am using Version 0.23.4 of Pandas

**Comment by parrt** [comment]
That looks scikit-learn; my pandas is 1.1.2.

**Comment by parrt** [comment]
I think check the type of your training vectors going in.  it looks like pandas data frame still allows the deep parameter on copy:

```
pandas.DataFrame.copy(deep=True)
```

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.copy.html#pandas.DataFrame.copy

 actually looks like you might have something else going on. I don't see `axes` anywhere in my latest rfpimp:

```
X_train = X_sample.copy(deep=False,axes=True) # shallow copy
```

that's where you say the error is.  maybe check the version of rfpimp.
