### ISSUE TITLE
Incorrect references to sklearn?

### ISSUE THREAD

**Issue by mgandaman** [parrt/random-forest-importances#47]
Hello,

I have rfpimp ver 1.3.6 installed as well as sklearn 0.24.1. When I ran a script that used them, I got this error
  File "C:\...\anaconda3\envs\...\lib\site-packages\rfpimp.py", line 16, in <module>
    from sklearn.ensemble.forest import _generate_unsampled_indices
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'

I dug into it and found that sklearn.ensemble.forest is, in my version, sklearn.ensemble._forest and _generate_unsampled_indices does reside there. 
While it's possible that something is wrong on my end, my guess is that sklearn has changed? I may change rfpimp.py on my own to match sklearn. I hope it doesn't break my computer. Thanks!

**Comment by parrt** [comment]
Hi. Yep. I gotta do a version check in the code. thanks!

**Comment by huanfachen** [comment]
According to this [discussion](https://github.com/scikit-learn-contrib/forest-confidence-interval/issues/86):

> The sklearn.ensemble.forest module is deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.

I tested with rfpimp 1.3.2, it doesn't work with sklearn 0.22 as it requires ```from sklearn.ensemble.forest import _generate_unsampled_indices```.

Does the laster rfpimp (v.1.3.6) work with sklearn 0.22?

**Comment by parrt** [comment]
I will have do some checking on the various versions... sorry for the hassle

**Comment by parrt** [comment]
I think the issue is that 0.22 required two arguments and not three but it still used:
 
 ```
        from sklearn.ensemble.forest import _get_n_samples_bootstrap
```

but 0.24 is going to move that module. 0.23 is working for me at the moment but I will try to back up to 0.22 and see if it still works with rfpimp 1.3.6

**Comment by huanfachen** [comment]
> I think the issue is that 0.22 required two arguments and not three but it still used:
> 
> ```
>        from sklearn.ensemble.forest import _get_n_samples_bootstrap
> ```
> 
> but 0.24 is going to move that module. 0.23 is working for me at the moment but I will try to back up to 0.22 and see if it still works with rfpimp 1.3.6. Yep that works. I am unable to roll back to 0.21.3 however with pip so I'm not sure about 0.21. So, yes, it does work with 0.22, @huanfachen.

Thanks @parrt . Sorry for my typo in my msg. 

I confirm that rfpimp 1.3.2 works with sklearn v0.22 but not with sklearn v0.24.

**Comment by parrt** [comment]
Ok, please try 1.3.7 rfpimp.  should work for you now.

**Comment by huanfachen** [comment]
@parrt I saw that 1.3.7 rfpimp is on pip but not conda-forge. Is it possible to upload it to conda-forge?

**Comment by parrt** [comment]
hi. sorry. a single source is best.
