### ISSUE TITLE
Full importances function always uses model.score

### ISSUE THREAD

**Issue by feribg** [parrt/random-forest-importances#5]
I was wondering if a PR that changes that behaviour to instead use the score form a passed `metric` function would be better, while still defaulting to `model.score` if not set. This is the current behaviour for `permuation_importances_raw`, however that function doesn't support grouping of the features. In many cases accuracy or R2 are not the most suitable scores.

**Comment by parrt** [comment]
Makes sense! Wanna make a PR?
