### ISSUE TITLE
score() takes from 2 to 3 positional arguments but 4 were given: dropcol_importance

### ISSUE THREAD

**Issue by vivekruhela** [parrt/random-forest-importances#52]
Hello,

I am trying to find important features from trained CatBoost model using dropcol_importance. I have already tried dropcol_importance with SVC and XGBoost and it is working fine but with CatBoost model, I am facing an error that I am not able to debug. 

My code is as follows:

    def model_train(clf, X_train,X_test,y_train,y_test,i):
        clf.fit(X_train, y_train)#
        model_name = 'fold_' + str(i) + '_catboost.sav'
        pickle.dump(clf,open(model_name,'wb'))
        scores = score_computation(clf,X_test,y_test,X_train,y_train)
        return scores

    weights = {0:1, 1:19.22}
    clf = CatBoostClassifier(depth=10,
                             learning_rate=0.1,
                             l2_leaf_reg = 2,
                             n_estimators = 40,
                             loss_function='Logloss',
                             thread_count = 15,
                             verbose=False,
                             task_type="GPU",
                             devices='0:1',
                             class_weights = weights)
    print('************************************')
    print('Now starting the training of Fold-',i,' ....')
    X_train, X_test = pd.DataFrame(X[train_index]), pd.DataFrame(X[test_index])
    y_train, y_test = Y[train_index], Y[test_index]
    %time scores = model_train(clf,X_train,X_test,y_train,y_test,i)
    print('Model training is complete. Now getting best features...')
    %time imp = dropcol_importances(clf,X_train,y_train,X_test,y_test)

The error message is: `score() takes from 2 to 3 positional arguments but 4 were given`. Here is the traceback.

    <timed exec> in <module>

    ~/miniconda3/lib/python3.7/site-packages/rfpimp.py in dropcol_importances(model, X_train, y_train, X_valid, y_valid, metric, sample_weights)
         330         baseline = metric(model_, X_valid, y_valid, sample_weights)
         331     else:
    --> 332         baseline = model_.score(X_valid, y_valid, sample_weights)
        333     imp = []
        334     for col in X_train.columns:

    TypeError: score() takes from 2 to 3 positional arguments but 4 were given`

I also tried with `dropcol_importances(clf,X_train,y_train)` but no luck. I wonder the same script for dropcol_importance is working with other models but not with CatBoost. Please suggest how to fix this. Thanks.

**Comment by vivekruhela** [comment]
I fixed this issue by some minor changes in the `dropcol_importances` function. I took the code from source file and change the `model_.score` according to my model (CatBoost). Here is the code I've used for `dropcol_importances`.

    def dropcol_importances(model, X_train, y_train, X_valid=None, y_valid=None, metric=None, sample_weights=None):
        if X_valid is None: X_valid = X_train
        if y_valid is None: y_valid = y_train
        model_ = clone(model)
        model_.random_state = 999
        model_.fit(X_train, y_train)
        if callable(metric):
            baseline = metric(model_, X_valid, y_valid)
        else:
            baseline = model_.score(X_valid, y_valid)
        imp = []
        for col in tqdm(X_train.columns):
            model_ = clone(model)
            model_.random_state = 999
            model_.fit(X_train.drop(col,axis=1), y_train)
            if callable(metric):
                s = metric(model_, X_valid.drop(col,axis=1), y_valid)
            else:
                s = model_.score(X_valid.drop(col,axis=1), y_valid)
            drop_in_score = baseline - s
            imp.append(drop_in_score)
        imp = np.array(imp)
        I = pd.DataFrame(data={'Feature':X_train.columns, 'Importance':imp})
        I = I.set_index('Feature')
        I = I.sort_values('Importance', ascending=False)
       return

**Comment by parrt** [comment]
Hi. sorry for delay. started new job at google and I'm overwhelmed...
